Phasmo Ascension Update v0.9.0.8
GlitchedMythos/se-widgets pull request #82
Opened 2023-09-04 18:59 UTC by AshKapow

Release Notes: https://store.steampowered.com/news/app/739630

Fingerprints/Fingies replaced by Ultraviolet
Smudge replaced by Incense
Candle replaced by Firelight

2023-10-01 17:05 UTC, jrowelltech commented
I've done a quick review on this, but there's the section of setting the paths that I don't feel I have expertise onto approve. Want me to test and provide feedback/review?

2024-08-21 23:02 UTC, billyjbryant requested changes

2024-08-21 23:02 UTC, billyjbryant commented on phasmophobia_evidence_tracker/widget.js
> -  fingerprints: "fingerprints",
Might be useful to keep the match for `fingerprints` and `fingies` for backwards compatibility.

2024-08-21 23:02 UTC, billyjbryant commented on phasmophobia_evidence_tracker/widget.json
> +    "value": "!gu",
Same here, can we preserve backwards compatibility

2024-10-17 18:06 UTC, AshKapow commented
@billyjbryant apologies for the delay, but this has now been added

2025-04-21 23:00 UTC, billyjbryant approved these changes

2025-12-30 17:21 UTC, closed without merging